[book]
title = "A Field Guide to Bounded Intelligence"
authors = ["Alexey Kopytko"]
language = "en"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/sanmai/bounded-intelligence"
additional-js = ["theme/footer.js"]
additional-css = ["theme/footer.css"]
